services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.1.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    ports:
      - "127.0.0.1:9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:9.1.4
    container_name: kibana
    ports:
      - "127.0.0.1:5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch

  init-kibana:
    image: curlimages/curl:latest
    container_name: init-kibana
    depends_on:
      - kibana
    entrypoint: >
      /bin/sh -c "
        echo 'Waiting for Kibana...'
        until curl -s http://kibana:5601/api/status | grep -q '\"overall\":{\"level\":\"available\"'; do
          sleep 5;
        done;
        echo 'Creating data view...'
        curl -X POST http://kibana:5601/api/data_views/data_view -H 'kbn-xsrf: true' -H 'Content-Type: application/json' -d '{\"data_view\": {\"title\": \"${INDEX_NAME}\", \"name\": \"My Index View\", \"timeFieldName\": \"@timestamp\"}}'
      "