[tools]
python = "3.13.7"

[env]
_.python.venv = { path = ".venv", create = true } # This will create Python virtual environment unless existing

[tasks.venv]
description = "Install Python requirements"
run = [
    "pip install -r requirements.txt",
    "[ ! -e .env ] && cp .env.template .env"
]

[tasks.infra-up]
description = "Start necessary Docker containers"
run = "docker compose up -d"

[tasks.infra-down]
description = "Start necessary Docker containers"
run = [
    "docker compose kill",
    "docker compose down"
]

[tasks.populate-elastic]
description = "Run Python script for populating Elastic"
run = "python populate-elastic.py"
